### ISSUE TITLE
there are some shift-reduce conflicts int grammar.y file

### ISSUE THREAD

**Issue by czmecho** [BourgondAries/Unnamed-Language#1]
When I used the bison to produce a grammar.tab.c file and grammar.tab.h file ,there are some shift-reduce conflicts.in the grammar.output file,there are some tips:
```
State 70 conflicts: 13 reduce/reduce
State 90 conflicts: 1 shift/reduce
State 91 conflicts: 1 shift/reduce
State 92 conflicts: 1 shift/reduce
State 93 conflicts: 1 shift/reduce
```

**Comment by BourgondAries** [comment]
I've been working on implementing a hand written lexer and parser so I think I'll have to edit out the bison and flex parts.

**Comment by czmecho** [comment]
@BourgondAries Thanks.
